apiVersion: v1
kind: Service
metadata:
  name: web-svc
  labels:
    env: production

spec:
  selector:
    env: production
  type: NodePort
  ports:
    - nodePort: 30000
      port: 80
      targetPort: 80